sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache:
  cargo: true
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose